### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by pickfire** [kingspp/RPi-AUI#18]
Is it okay to merge feature and requirement to [README.md](https://github.com/kingspp/Raspberry-Pi-AUI/blob/master/README.md). *Example*:

### Features:
 - [x] Searches plain text, HTML, and XML
 - [x] Word or phrase searching
 - [ ] Fuzzy matching
 - [ ] Incremental updating of indexes
 - [ ] Indexing of remote web sites

### Requirements:
 - Python 2.2 or higher
 - Enough disk space to hold the indexes (approximately 2x original data size)

**Comment by kingspp** [comment]
Sure, If it helps the User, then its a must.

**Comment by pickfire** [comment]
> Sure, If it helps the User, then its a must.
> @kingspp 

I have an idea which does not help the user.
I suggest that the title in [README.md](https://github.com/kingspp/Raspberry-Pi-AUI/blob/master/README.md#raspberry-pi-aui-v62) should be change to a [figlet][1] by searching at [duckduckgo](https://ddg.gg/) with option shown at [figlet][1] such as `figlet [option] [keyword]` like this [example](https://duckduckgo.com/?q=figlet+speed+AUI).
What do you think?

[1]: http://www.figlet.org/

**Comment by kingspp** [comment]
Most of us use google. Lets keep it as simple and elegant as possible. I have see those in torrents, but not anywhere in Github, If you think it would help users reach out to the repo, then we can change.

**Comment by pickfire** [comment]
On 03/01/2015 20:09, Prathyush wrote:
> Most of us use google. Lets keep it as simple and elegant as possible.
> I have see those in torrents, but not anywhere in Github, If you think
> it would help users reach out to the repo, then we can change.

No I mean to just search for `figlet speed AUI` in duckduckgo just to
set the title in README.md, just try to click on this link to get that:
https://duckduckgo.com/?q=figlet+speed+AUI&t=raspberrypi
____________  _________
___    __  / / ____  _/
__  /| _  / / / __  /
_  ___ / /_/ / __/ /
/_/  |_\____/  /___/

Do you know what I mean?
     Ivan Tham

**Comment by kingspp** [comment]
Actually AUI is already present in Arch linux for x86. So you need a different name

**Comment by pickfire** [comment]
What about this? Created by vim in Raspberry Pi. Demo:

![term1](https://cloud.githubusercontent.com/assets/4687791/5628919/89747d5c-95e8-11e4-8441-56bddd36e733.png)

Code:

![term2](https://cloud.githubusercontent.com/assets/4687791/5628920/897bb5ea-95e8-11e4-954f-c572a8729c98.png)

**Comment by kingspp** [comment]
Looks cool

**Comment by pickfire** [comment]
Take a look at https://github.com/pickfire/dotfiles, give any comment if you like and pull requests is welcome.
I hope that you put your dotfiles too.

**Comment by kingspp** [comment]
Sorry to break it to you. I dont work with VIM. Changed my default editor to NANO

**Comment by pickfire** [comment]
Does nano uses the key bindings similar to emacs?

**Comment by kingspp** [comment]
Never used those things

**Comment by kingspp** [comment]
Did you include figlet?

**Comment by pickfire** [comment]
I have included figlet in `main.sh`. If you doesn't like it, you can change it. And if it is okay, then you can delete those `title()`. And in **README.md**, I haven't included a figlet.

**Comment by kingspp** [comment]
Yes it can be included...
