### ISSUE TITLE
Look at this

### ISSUE THREAD

**Issue by pickfire** [kingspp/RPi-AUI#25]
https://github.com/altercation/archinit/blob/master/archinit

Do you think we should add this to our README.md for ideas?

**Comment by pickfire** [comment]
This too:

https://github.com/altercation/atypical

**Comment by pickfire** [comment]
And should we do the following?

1. move the archi.sh to RPi-AUI/archi.sh and not RPi-AUI/AUI/archi.sh
2. rename AUI to aui
3. add an app.sh in AUI to manage and install application
4. add help pages to archi.sh

you could put tick like this:

```
- [x] for a tick
- [ ] for no tick
```

**Comment by kingspp** [comment]
It looks complicated

**Comment by pickfire** [comment]
Add that to to-do list?

**Comment by pickfire** [comment]
This site had good CONTRIBUTING.md except that we doesn't need that git flow as there is less people:
https://github.com/powerline/powerline

**Comment by pickfire** [comment]
This [style guide](https://google-styleguide.googlecode.com/svn/trunk/shell.xml?showone=Indentation#Indentation, "google styleguide"). Okay?

**Comment by kingspp** [comment]
For what purpose?

On Sun, Jan 18, 2015 at 2:32 PM, pickfire <notifications@github.com> wrote:

> This style guide
> <https://google-styleguide.googlecode.com/svn/trunk/shell.xml?showone=Indentation#Indentation,>.
> Okay?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kingspp/RPi-AUI/issues/25#issuecomment-70401092>.
>



-- 
With Regards,
Prathyush S.P
Code-Tronix <http://codetronix.in/>

**Comment by pickfire** [comment]
On 18/01/2015 21:16, Prathyush wrote:
> For what purpose?

Using 2 spaces for indentation would be better than using a tab.

**Comment by kingspp** [comment]
I am using notepad++, tab space is said to be long, when it is said to be committed to the the github

**Comment by pickfire** [comment]
What do you mean **_long**_?

**Comment by kingspp** [comment]
I mean it takes two tab spaces in github, but only a single tab in notepad++

**Comment by pickfire** [comment]
How long is a single tab? I think it is almost the same for a tab and two spaces?
