### ISSUE TITLE
Is 6.2 a bit too fast?

### ISSUE THREAD

**Issue by pickfire** [kingspp/RPi-AUI#27]

**Comment by kingspp** [comment]
Lots of errors in the latest commit. Verify the complete package before merging a pull request

**Comment by pickfire** [comment]
Lots of errors? Which script?

**Comment by kingspp** [comment]
The main script.

**Comment by pickfire** [comment]
which line?

**Comment by kingspp** [comment]
When i run aui . It gives 5 errors. (File not found)

**Comment by pickfire** [comment]
Sorry, I haven't fix the `install.sh` and `uninstall.sh`. Do you think the old tags such as 0.1 is needed?

**Comment by kingspp** [comment]
I thought of giving this as  v1. I was in a hurry and ran down till v6.

**Comment by pickfire** [comment]
The tags seems a bit too fast and where is **v2**, **v3** and **v5**?

**Comment by kingspp** [comment]
I thought the same, to release updates in decimal, so how will it look, if its called v1.0 ?

**Comment by pickfire** [comment]
Never mind. Those tags are normal.
