### ISSUE TITLE
Tables

### ISSUE THREAD

**Issue by pickfire** [kingspp/RPi-AUI#31]
Which is better? **ASCII** or **UTF-8**?

**UTF-8**
![utf8](http://s13.postimg.org/8itx2q9yv/vim.png)

**ASCII**
![ascii](http://s23.postimg.org/5luw94k3v/table.png)

**Comment by kingspp** [comment]
Both of them looks good.. You choose.. :)

**Comment by pickfire** [comment]
UTF-8
